
// class WebSocketRequestHandler;
// class WebSocketServer;
// class RequestHandlerFactory;
class Singleton;
class Shader;
class GameSound;
class GameMusic;
class FontWrapper;
class UIComponent;
class GameGUI;
class GameAI;
class GameNetwork;
class GameFluid;
class GameOrgNode;
class GameOrg;
class GamePlantNode;
class GamePlant;
class GameEnt;
class GameBlock;
class GamePageHolder;
class VolumeWrapper;
class ThreadPoolWrapper;
class GameLogic;
class GamePhysics;
class GameWorld;
class DynBuffer;
